# Generated by Django 5.2 on 2025-07-30 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('units_of_measurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('handle', models.TextField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('tags', models.JSONField(blank=True, default=dict, null=True)),
                ('featured_image', models.TextField(blank=True, max_length=10, null=True)),
                ('images', models.JSONField(blank=True, default=dict, null=True)),
                ('prices_cf', models.JSONField(blank=True, default=dict, null=True)),
                ('prices_sf', models.JSONField(blank=True, default=dict, null=True)),
                ('prices_box', models.JSONField(blank=True, default=dict, null=True)),
                ('featured_pcf', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('featured_psf', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('featured_pbox', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('quantity_in_box', models.SmallIntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('depth', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('liters', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('extra_shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, db_column='brand_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='brands.brand')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('unit_of_measurement', models.ForeignKey(blank=True, db_column='unit_of_measurement_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='units_of_measurement.unitofmeasurement')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
    ]
