# Generated by Django 5.2 on 2025-07-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_depth_alter_product_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra_shipping_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
    ]
