# Generated by Django 5.2 on 2025-07-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='names',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
