# Generated by Django 5.2 on 2025-08-07 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work_schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.SmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_working_day', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='work_schedules.workschedule')),
            ],
            options={
                'db_table': 'schedule_details',
                'constraints': [models.CheckConstraint(condition=models.Q(('day_of_week__gte', 0), ('day_of_week__lte', 6)), name='day_of_week_valid_range'), models.CheckConstraint(condition=models.Q(('is_working_day', False), ('end_time__gt', models.F('start_time')), _connector='OR'), name='working_day_time_check')],
            },
        ),
    ]
