# Generated by Django 5.2 on 2025-07-30 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch_offices', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchoffice',
            name='company',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
