# Generated by Django 5.2 on 2025-07-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=255)),
                ('role_id', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('avatar', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('settings', models.JSONField(default=dict)),
                ('shortcuts', models.JSONField(default=list)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('agreed', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('become_seller', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
    ]
