# Generated by Django 5.2 on 2025-08-07 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(max_length=50)),
                ('incident_date', models.DateField()),
                ('observation', models.TextField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_to_pay', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='employees.employee')),
                ('reported_by', models.ForeignKey(db_column='reported_by', on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Employee Incident',
                'verbose_name_plural': 'Employee Incidents',
                'db_table': 'employee_incidents',
            },
        ),
    ]
