# Generated by Django 5.2.4 on 2025-08-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_movements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(blank=True, choices=[('entry', 'Entry'), ('exit', 'Exit'), ('adjustment', 'Adjustment')], max_length=50, null=True),
        ),
    ]
