# Generated by Django 5.2.4 on 2025-08-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='notes',
            new_name='observation',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_type',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='worked_hours',
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_worked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
