# Generated by Django 5.2.4 on 2025-08-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_rename_notes_attendance_observation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time_worked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
