# Generated by Django 5.2 on 2025-08-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='company_or_branch_office',
            field=models.BooleanField(default=1),
        ),
    ]
