# Generated by Django 5.2 on 2025-07-30 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('job_positions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_position',
            field=models.ForeignKey(blank=True, db_column='job_position_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_positions.jobposition'),
        ),
    ]
