# Generated by Django 5.2 on 2025-08-09 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_initial'),
        ('warehouses', '0002_warehouse_company_or_branch_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_column='warehouse_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse'),
        ),
    ]
